services:
  ollama:
    image: ollama/ollama
    container_name: ollama-docker-compose
    ports:
      - "11434:11434"
    command: ollama run mistral

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      VECTOR_STORE_TYPE: pgVector

